Feature update schema docs
bcgov/aries-vcr pull request #711
Opened 2021-11-09 22:06 UTC by wadeking98

added documentation to direct issuers on how to update credential schemas to support schema labels, highlighted attributes, credential titles, etc

2021-11-10 13:09 UTC, WadeBarnes commented
Please rebase your changes on the latest from the main branch to eliminate the merge from your commit history.

2021-11-10 13:31 UTC, WadeBarnes requested changes

2021-11-10 13:31 UTC, WadeBarnes commented on docs/README.md
> +Aries-vcr has undergone updates to the issuer credential schema. See the latest updates and how to apply them [here](Schema-changes.md)
```suggestion
Aries-vcr has undergone updates to the issuer credential schema. See the latest updates and how to apply them [here](Schema-changes.md).
```

2021-11-10 13:31 UTC, WadeBarnes commented on docs/README.md
> +  - [Updates to Credential Schema](###updates-to-credential-schema)
The table of content links (all of them) are broken.  I believe the proper syntax for a TOC link is to use a single `#`.  Please fix.

2021-11-10 13:31 UTC, WadeBarnes commented on docs/Schema-changes.md
> +The Aries-vcr application is undergoing changes to enhance user experience on applications such as Orgbook. The primary change to the Aries-vcr application is in the way that credential schemas are i
```suggestion
The Aries VCR application is undergoing changes to enhance user experience on applications such as Orgbook. The primary change to the Aries-vcr application is in the way that credential schemas are processed.  
```

Please replace 'Aries-vcr' with 'Aries VCR' throughout to keep things consistent with the rest of the documentation.

2021-11-10 13:31 UTC, WadeBarnes commented on docs/Schema-changes.md
> +Included below are a list of optional changes to credential schemas that issuers may be interested in making. For the purpose of clearly displaying how these changes are being used, we've provided ex
"we've provided examples of the credential changes in the new Orgbook site."  Provide a link to the repository so it is clear what code is being used for the examples.

2021-11-10 13:31 UTC, WadeBarnes commented on docs/Schema-changes.md
> +*Figure 4.1: Example attribute key*
Figure title text is displaying inline with the figure rather than under it.

2021-11-10 13:31 UTC, WadeBarnes commented on docs/Schema-changes.md
> +*Figure 4.2: Attribute label and value*
Figure title text is displaying inline with the figure rather than under it.

2021-11-10 13:31 UTC, WadeBarnes commented on docs/Schema-changes.md
> +To set the attribute label simply edit the claim label for the attribute in question. To do so, in `metadata->labels->attributes->translations->[locale]->label` change the `name` field to your desire
Consider using the more standard `.` notation for describing the path in the json (throughout the document).  For example:
- `metadata->labels->attributes->translations->[locale]->label` should be `metadata.labels.attributes.translations.[locale].label`

2021-11-10 22:13 UTC, ianco requested changes
Docs should match against the registration message structure

2021-11-10 22:13 UTC, ianco commented on docs/Schema-changes.md
> +    "topic": [
This message structure doesn't match the structure passed to the `/registration` endpoint nor the structure of the message passed from one agent to the other as part of the registration protocol.

Is this the message structure internal to the new Issuer Agency?

2021-12-10 19:39 UTC, WadeBarnes requested changes
A few small changes.

@ianco, could you review the schema example again please?

2021-12-10 19:39 UTC, WadeBarnes commented on docs/Schema-changes.md
> +The Aries VCR application is undergoing changes to enhance user experience on applications such as Orgbook. The primary change to the Aries VCR application is in the way that credential schemas are i
```suggestion
The Aries VCR application is undergoing changes to enhance user experience on applications such as Orgbook. The primary change to the Aries VCR application is in the way that credential schemas are processed.  
```

2021-12-10 19:39 UTC, WadeBarnes commented on docs/Schema-changes.md
> +If the credential title is not specified in a credential schema, or there is no claim label to match the credential title, then applications such as Orgbook may instead use the registration number of
```suggestion
If the credential title is not specified in a credential schema, or there is no claim label to match the credential title, then applications such as Orgbook may instead use the registration number of the entity holding the credential. See figure 3 for an example.
```

2021-12-10 19:39 UTC, WadeBarnes commented on docs/Schema-changes.md
> +To incorporate these optional changes, Aries VCR recommends reviewing the new schema attributes and how to add them to your credential schema in the section below. The following example JSON snippet
```suggestion
To incorporate these optional changes, Aries VCR recommends reviewing the new schema attributes and how to add them to your credential schema in the section below. The following example JSON snippet is from the `issuer_registration.credential_types[item]` section of the registration.registries.ca schema.
```

2021-12-10 19:39 UTC, WadeBarnes commented on docs/Schema-changes.md
> +In order to set the schema label add the following JSON object to `issuer_registration.credential_types[item]`
```suggestion
In order to set the schema label add the following JSON object to `issuer_registration.credential_types[item]`:
```

2021-12-10 19:39 UTC, WadeBarnes commented on docs/Schema-changes.md
> +To set the credential title and highlighted attributes setup Aries VCR issuer controller and add the following YAML object to `issuers.myorg.credential_types[index]` in `services.yaml`. Figure 4.1 sh
`Make sure to do this for each`

Please complete the sentence.

2021-12-10 19:39 UTC, WadeBarnes commented on docs/Schema-changes.md
> +highlighted attribute keys and the credential title key refer to the attribute names on each of the attributes in the schema. An example is shown in figure 4.2. Highlighted attributes will appear on
```suggestion
Highlighted attribute keys and the credential title key refer to the attribute names on each of the attributes in the schema. An example is shown in figure 4.2. Highlighted attributes will appear on credential cards in the order they're listed on the schema. Example: attribute #1 will appear above attribute #2 on this credential card.
```

2021-12-10 19:39 UTC, WadeBarnes commented on docs/Schema-changes.md
> +To set the attribute label simply edit the claim label for the attribute in question. To do so in your credential schema, go to `issuer_registration.claim_labels.<YOUR ATTRIBUTE KEY>.[locale]` change
```suggestion
To set the attribute label simply edit the claim label for the attribute in question. To do so in your credential schema, go to `issuer_registration.claim_labels.<YOUR ATTRIBUTE KEY>.[locale]` change the field to your desired label as seen in figure 4.4 where we change the `reason_description` from `Reason` to `DEMO`. See figure 4.5 for the resulting change in Orgbook.
```

2021-12-10 19:50 UTC, ianco requested changes

2021-12-10 19:50 UTC, ianco commented on docs/Schema-changes.md
> +~~~
This looks good.  Probably worth pointing out where this format of message is used (is it the format provided to the new issuer agency?) and linking to the demo issuer/controller (https://github.com/bcgov/aries-vcr-issuer-controller/tree/main/issuer_controller/config#changes-for-schema-localization), which has applied a corresponding set of changes, and represents the changes that the current set of issuers will need to make.

2021-12-10 21:26 UTC, ianco commented
Some commits are missing DCO signoff

2021-12-10 23:18 UTC, WadeBarnes approved these changes

2021-12-11 19:55 UTC, ianco approved these changes

2021-12-12 03:17 UTC, merged